AppWeb/Controllers/AutoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppWeb.Models;
using Microsoft.AspNetCore.Authorization;

namespace AppWeb.Controllers
{
    [Authorize(Policy = "AdminPolicy")]
    public class AutoController : Controller
    {
        private readonly ProyectoContext _context;

        public AutoController(ProyectoContext context)
        {
            _context = context;
        }

        // GET: Auto
        public async Task<IActionResult> Index()
        {
            var proyectoContext = _context.Vehiculos.Include(v => v.Imagen);
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            return View(await proyectoContext.ToListAsync());
        }

        // GET: Auto/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null || _context.Vehiculos == null)
            {
                return NotFound();
            }
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            var vehiculo = await _context.Vehiculos
                .Include(v => v.Imagen)
                .FirstOrDefaultAsync(m => m.IdAuto == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        // GET: Auto/Create
        public IActionResult Create()
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            ViewData["ImagenId"] = new SelectList(_context.Imagens, "IdImagen", "ImagenData");
            return View();
        }

        // POST: Auto/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Nombre,Marca,Año,Color")] Vehiculo vehiculo, IFormFile imagenData)
        {
            if (ModelState.IsValid)
            {
                try
                {
                    if (imagenData != null && imagenData.Length > 0)
                    {
                        // Procesar la carga de archivos
                        using (var memoryStream = new MemoryStream())
                        {
                            await imagenData.CopyToAsync(memoryStream);
                            Imagen imagen = new Imagen
                            {
                                ImagenData = memoryStream.ToArray(),
                                ImagenMimeType = "image/jpeg"  // Asignar el tipo de imagen directamente como JPEG
                            };

                            // Asociar la imagen al vehículo
                            vehiculo.Imagen = imagen;
                        }
                    }

                    // Agregar el vehículo al contexto y guardar en la base de datos
                    _context.Add(vehiculo);
                    await _context.SaveChangesAsync();

                    // Asignar el IdAuto del vehículo recién creado al campo VehiculoId de la imagen
                    vehiculo.Imagen.VehiculoId = vehiculo.IdAuto;
                    vehiculo.Imagen.ImagenMimeType = $"{vehiculo.Nombre.Replace(" ", "")}.jpg"; // Asignar el nombre de la imagen
                    await _context.SaveChangesAsync(); // Guardar la imagen con el VehiculoId y nombre asignados

                    return RedirectToAction(nameof(Index));
                }
                catch (Exception ex)
                {
                    // Registrar el error, puedes usar la consola o un sistema de registro
                    Console.WriteLine($"Error al guardar datos: {ex.Message}");
                    ModelState.AddModelError(string.Empty, "Error al guardar los datos. Por favor, inténtelo de nuevo.");
                }
            }

            return View(vehiculo);
        }


        // GET: Auto/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null || _context.Vehiculos == null)
            {
                return NotFound();
            }
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            var vehiculo = await _context.Vehiculos.FindAsync(id);
            if (vehiculo == null)
            {
                return NotFound();
            }
            ViewData["ImagenId"] = new SelectList(_context.Imagens, "IdImagen", "IdImagen", vehiculo.ImagenId);
            return View(vehiculo);
        }

        // POST: Auto/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, Vehiculo vehiculo, IFormFile imagenData)
        {
            if (id != vehiculo.IdAuto)
            {
                ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    // Si se proporciona una nueva imagen, procesarla y actualizar la imagen asociada al vehículo
                    if (imagenData != null && imagenData.Length > 0)
                    {
                        using (var memoryStream = new MemoryStream())
                        {
                            await imagenData.CopyToAsync(memoryStream);
                            Imagen nuevaImagen = new Imagen
                            {
                                ImagenData = memoryStream.ToArray(),
                                ImagenMimeType = "image/jpeg"  // Asignar el tipo de imagen directamente como JPEG
                            };

                            // Asociar la nueva imagen al vehículo
                            vehiculo.Imagen = nuevaImagen;
                        }
                    }

                    _context.Update(vehiculo);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!VehiculoExists(vehiculo.IdAuto))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            ViewData["ImagenId"] = new SelectList(_context.Imagens, "IdImagen", "IdImagen", vehiculo.ImagenId);
            return View(vehiculo);
        }
        // GET: Auto/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null || _context.Vehiculos == null)
            {
                return NotFound();
            }
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            var vehiculo = await _context.Vehiculos
                .Include(v => v.Imagen)
                .FirstOrDefaultAsync(m => m.IdAuto == id);
            if (vehiculo == null)
            {
                return NotFound();
            }

            return View(vehiculo);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;

            // Obtener el vehículo y sus imágenes asociadas
            var vehiculo = await _context.Vehiculos
                .Include(v => v.Imagens)
                .FirstOrDefaultAsync(v => v.IdAuto == id);

            if (vehiculo != null)
            {
                // Verificar si las imágenes aún existen antes de eliminarlas
                foreach (var imagen in vehiculo.Imagens.ToList())
                {
                    _context.Imagens.Remove(imagen);
                }

                // Guardar cambios después de eliminar las imágenes
                await _context.SaveChangesAsync();

                // Eliminar el vehículo después de eliminar las imágenes
                _context.Vehiculos.Remove(vehiculo);

                await _context.SaveChangesAsync();
            }

            return RedirectToAction(nameof(Index));
        }






        private bool VehiculoExists(int id)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            return (_context.Vehiculos?.Any(e => e.IdAuto == id)).GetValueOrDefault();
        }
    }
}

AppWeb/Controllers/RolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AppWeb.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc.Filters;



namespace AppWeb.Controllers
{
    [Authorize(Policy = "AdminPolicy")]
    public class RolsController : Controller
    {
        private readonly ProyectoContext _context;

        public RolsController(ProyectoContext context)
        {
            _context = context;
        }

        // GET: Rols
        public async Task<IActionResult> Index()
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            return _context.Rols != null ? 
                          View(await _context.Rols.ToListAsync()) :
                          Problem("Entity set 'ProyectoContext.Rols'  is null.");
        }
        // GET: Rols/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            if (id == null || _context.Rols == null)
            {
                return NotFound();
            }

            var rol = await _context.Rols
                .FirstOrDefaultAsync(m => m.IdRol == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // GET: Rols/Create
        public IActionResult Create()
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            return View();
        }

        // POST: Rols/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdRol,NombreRol")] Rol rol)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            if (ModelState.IsValid)
            {
                _context.Add(rol);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        // GET: Rols/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            if (id == null || _context.Rols == null)
            {
                return NotFound();
            }

            var rol = await _context.Rols.FindAsync(id);
            if (rol == null)
            {
                return NotFound();
            }
            return View(rol);
        }

        // POST: Rols/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdRol,NombreRol")] Rol rol)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            if (id != rol.IdRol)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(rol);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!RolExists(rol.IdRol))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(rol);
        }

        // GET: Rols/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            if (id == null || _context.Rols == null)
            {
                return NotFound();
            }

            var rol = await _context.Rols
                .FirstOrDefaultAsync(m => m.IdRol == id);
            if (rol == null)
            {
                return NotFound();
            }

            return View(rol);
        }

        // POST: Rols/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            ViewData["nombreUsuario"] = HttpContext.User?.Identity?.Name;
            if (_context.Rols == null)
            {
                return Problem("Entity set 'ProyectoContext.Rols'  is null.");
            }
            var rol = await _context.Rols.FindAsync(id);
            if (rol != null)
            {
                _context.Rols.Remove(rol);
            }
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool RolExists(int id)
        {
          return (_context.Rols?.Any(e => e.IdRol == id)).GetValueOrDefault();
        }
    }
}

AppWeb/Views/Master/IndexGerencia.cshtml
@{
    ViewData["Title"] = "Home Page";
}
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <style>
        body {
            background-color: antiquewhite; /* Fondo negro */
            color: #FFFFFF; /* Letras blancas */
        }

        .card {
            margin-bottom: 20px;
            background-color: #FFFFFF; /* Cartas de color blanco por defecto */
            color: #000000; /* Letras negras por defecto */
            transition: background-color 0.3s ease; /* Transición suave */
        }

            .card:hover {
                background-color: #FF6B00; /* Color de las cartas al pasar el mouse */
            }

        .card-title {
            font-size: 22px; /* Tamaño de fuente un poco más pequeño para el mensaje de bienvenida */
            font-weight: bold; /* Negrita */
            font-family: 'Montserrat', sans-serif; /* Fuente Montserrat */
        }

        .card-body {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .nav-link {
            color: #FF6B00; /* Letras FF6B00 por defecto en "Ir" */
            font-size: 18px; /* Tamaño de letra más grande */
            text-decoration: none;
            transition: color 0.3s ease; /* Transición suave */
        }

        .card:hover .nav-link {
            color: #000000; /* Color de "Ir" al pasar el mouse */
        }

        .welcome-message {
            font-family: 'Montserrat', sans-serif; /* Fuente Montserrat para el mensaje de bienvenida */
            font-weight: bold; /* Negrita */
            margin-bottom: 10px; /* Margen inferior reducido */
            color: #000000;
        }

        .large-text {
            font-size: 28px; /* Tamaño de fuente más grande para el mensaje "¿Qué deseas hacer?" */
            font-weight: bold; /* Negrita */
            margin-top: 20px; /* Margen superior agregado */
            color: #FF6B00;
        }
    </style>
</head>
<body>
<div class="text-center">
        <h1 class="display-4" style="color: black;">Bienvenido, Gerente @ViewData["nombreUsuario"]</h1>


    <div class="col">
        <div class="card">
            <div class="card-body">
                <h5 class="card-title">Tarifa</h5>
                <a class="nav-link text-dark" asp-controller="Tarifa" asp-action="Index">Ir &rarr;</a>
            </div>
        </div>
    </div>
    <div class="col">
        <div class="card w-100">
            <div class="card-body">
                <h5 class="card-title">Reserva</h5>
                <a class="nav-link text-dark" asp-controller="Events" asp-action="Index">Ir &rarr;</a>
            </div>
        </div>
    </div>
</div>

    <!-- Bootstrap JS y dependencias (jQuery) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>

    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

AppWeb/Views/Master/IndexMaster.cshtml
@{
    ViewData["Title"] = "Index Master";
    var userIdClaim = User.FindFirst("IdRolClaim")?.Value;
}

<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>@ViewData["Title"]</title>

    <!-- Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@700&display=swap" rel="stylesheet">
    <style>
        body {
            background-color: antiquewhite; /* Fondo negro */
            color: #FFFFFF; /* Letras blancas */
            font-family: 'Montserrat', sans-serif; /* Fuente Montserrat */
        }

        .card {
            margin-bottom: 20px;
            background-color: #FFFFFF; /* Cartas de color blanco por defecto */
            color: #000000; /* Letras negras por defecto */
            transition: background-color 0.3s ease; /* Transición suave */
        }

            .card:hover {
                background-color: #FF6B00; /* Color de las cartas al pasar el mouse */
            }

        .card-title {
            font-size: 22px; /* Tamaño de fuente un poco más pequeño para el mensaje de bienvenida */
            font-weight: bold; /* Negrita */
            font-family: 'Montserrat', sans-serif; /* Fuente Montserrat */
        }

        .card-body {
            display: flex;
            justify-content: space-between;
            align-items: center;
        }

        .nav-link {
            color: #FF6B00; /* Letras FF6B00 por defecto en "Ir" */
            font-size: 18px; /* Tamaño de letra más grande */
            text-decoration: none;
            transition: color 0.3s ease; /* Transición suave */
        }

        .card:hover .nav-link {
            color: #000000; /* Color de "Ir" al pasar el mouse */
        }

        .welcome-message {
            font-family: 'Montserrat', sans-serif; /* Fuente Montserrat para el mensaje de bienvenida */
            font-weight: bold; /* Negrita */
            margin-bottom: 10px; /* Margen inferior reducido */
            color: #000000;
        }

        .large-text {
            font-size: 28px; /* Tamaño de fuente más grande para el mensaje "¿Qué deseas hacer?" */
            font-weight: bold; /* Negrita */
            margin-top: 20px; /* Margen superior agregado */
            color: #FF6B00;
        }
    </style>
</head>
<body>

    <div class="container mt-4">
        <div class="welcome-message">
            <h3 class="display-4">Bienvenido, Administrador @ViewData["nombreUsuario"]</h3>
        </div>

        <p class="large-text">¿Qué deseas hacer?</p>

        <hr class="mt-4">

        <div class="row row-cols-1 row-cols-md-2 g-4">
            <!-- Fila 1 -->
            <div class="col">
                <a href="@Url.Action("Index", "Rols")" class="card text-dark">
                    <div class="card-body">
                        <h5 class="card-title">Crear Roles</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>

            <div class="col">
                <a href="@Url.Action("Index", "Usuarios")" class="card text-dark">
                    <div class="card-body">
                        <h5 class="card-title">Crear Usuarios</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>

            <!-- Fila 2 -->
            <div class="col">
                <a href="@Url.Action("Index", "Imagens")" class="card text-dark">
                    <div class="card-body">
                        <h5 class="card-title">Imagen</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>

            <div class="col">
                <a href="@Url.Action("Index", "Auto")" class="card text-dark">
                    <div class="card-body">
                        <h5 class="card-title">Vehiculo</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>

            <div class="col">
                <a href="@Url.Action("Index", "Tarifa")" class="card text-dark">
                    <div class="card-body">
                        <h5 class="card-title">Tarifa</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>

            <!-- Fila 3 -->
            <div class="col">
                <a href="@Url.Action("Index", "Estadoes")" class="card text-dark">
                    <div class="card-body">
                        <h5 class="card-title">Estados</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>

            <!-- Fila 4 (Tarjeta grande) -->
            <div class="col">
                <a href="@Url.Action("Index", "Events")" class="card text-dark w-100">
                    <div class="card-body">
                        <h5 class="card-title">Reserva</h5>
                        <p class="card-text">Ir &rarr;</p>
                    </div>
                </a>
            </div>
        </div>
    </div>

    <hr class="mt-4">
    <p></p>



    <!-- Bootstrap JS y dependencias (jQuery) -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>